name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Zip source
        run: |
          tar -zcvf github-annual-summary.tar.gz ./font ./github4 ./static .gitignore ./annual_report.py ./app.py ./requirement.txt

      - name: Get version
        id: version
        run: |
          echo ::set-output name=version::$(< version)

      - name: Set Docker image metadata
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: sunchaserlilu/github-annual-summary
          flavor: latest=true
          tags: ${{ steps.version.outputs.version }}
          labels: |
            maintainer=admin@lilu.org.cn
            org.opencontainers.image.title=github-annual-summary
            org.opencontainers.image.version=${{ steps.version.outputs.version }}

      - name: Login in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
